networks:
    caddy:

volumes:
    ghostdrop_postgres_data:
    ghostdrop_redis_data:
    ghostdrop_minio_data:
    caddy_data:
    caddy_config:

services:
    postgres:
        image: postgres:latest
        environment:
            POSTGRES_USER: user
            POSTGRES_PASSWORD: password
            POSTGRES_DB: mydb
        ports:
            - "5433:5432"
        volumes:
            - ghostdrop_postgres_data:/var/lib/postgresql

    redis:
        image: redis:latest
        ports:
            - "6380:6379"
        volumes:
            - ghostdrop_redis_data:/data

    minio:
        image: minio/minio:latest
        environment:
            MINIO_ROOT_USER: minioadmin
            MINIO_ROOT_PASSWORD: minioadmin
        command: server /data
        ports:
            - "9000:9000"
        volumes:
            - ghostdrop_minio_data:/data

    caddy:
        image: caddy:latest
        restart: unless-stopped
        ports:
            - "80:80"
            - "443:443"
            - "443:443/udp"
        extra_hosts:
            - "host.docker.internal:host-gateway"
        volumes:
            - ./Caddyfile:/etc/caddy/Caddyfile
            - caddy_data:/data
            - caddy_config:/config
        networks:
            - caddy
